name: Generate Protobufs and Commit
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Important: this enables Actions to access all commits

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 # Choose the Go version to your preference

    - name: Install Protoc
      run: |
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
        sudo unzip protoc-3.15.8-linux-x86_64.zip -d /usr/local
        sudo chmod +x /usr/local/bin/protoc

    - name: Install Protoc Gen Go and Protoc Gen Go GRPC
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

    - name: Run Makefile
      run: make generate

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git diff --quiet && git diff --staged --quiet || (echo "Committing changes..." && git commit -m "Generate Protobufs")
        git push
